kind: Service
apiVersion: v1
metadata:
  name: fastapi-dev-service
  labels:
    app: fastapi-dev
spec:
  type: NodePort
  selector:
    app: fastapi-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
      name: http