namespace : app1

deployment:
  replicas: 2
  port: 8000

environment: "dev"

image: 
  repository: "708735187026.dkr.ecr.us-east-1.amazonaws.com/dev_ecr_repo"
  tag: v2

resourceLimits:
  memory: "256Mi"
  cpu: "500m"

resourceRequests:
  memory: "128Mi"
  cpu: "250m"

service:
  type: NodePort
  port: 80
  nodePort: 30080