kind: Deployment
apiVersion: apps/v1
metadata:
  name: fastapi-{{ .Values.environment }}-deployment
  labels:
    app: fastapi-{{ .Values.environment }}
  namespace: {{ .Values.namespace | default "app1" }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: fastapi-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: fastapi-{{ .Values.environment }}
    spec:
      containers:
        - name: fastapi
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.deployment.port | default 8000 }}
          env:
            - name: APP_VERSION
              value: {{ .Chart.AppVersion }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            limits:
              memory: {{ .Values.resourceLimits.memory }}
              cpu: {{ .Values.resourceLimits.cpu }}
            requests:
              memory: {{ .Values.resourceRequests.memory }}
              cpu: {{ .Values.resourceRequests.cpu }}
          