kind: Service
apiVersion: v1
metadata:
  name: fastapi-{{ .Values.environment }}-service
  labels:
    app: fastapi-{{ .Values.environment }}
  namespace: {{ .Values.namespace | default "app1" }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    app: fastapi-{{ .Values.environment }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.deployment.port | default 8000 }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      name: http